### PR TITLE
hello

### PR DESCRIPTION
**Pull request by zhangchenglin**
----------------------

### CODE REVIEW

**Comment by zhangchenglin** [comment]
It is recommended that you use a separate branch, and it may be better to generate a separate version number.

**Comment by zhangchenglin** [comment]
@Dibbyo456

**Comment by Dibbyo456** [comment]
>  be better to generate a separate version number.

It is complete fork with new version starting 1.0.0, check the release or packagist page.

> I don't think yours is a complete open source project?

It is open source. What makes you think it isn't ?

**Comment by zhangchenglin** [comment]
This is open source.  I did not express it well.  Makes you worry or unhappy.  very sorry.
 Are you ready to be independent from now on?  ?

**Comment by Dibbyo456** [comment]
> I did not express it well. Makes you worry or unhappy. very sorry.

No problem. 😃 

> Are you ready to be independent from now on?

Yes. I plan to do so. However I will not accept any "Feature Request"; Meaning don't expect any new features from me. But I will make it compatible with any new PHP versions and as well as fix any bugs that are worth fixing.

**Comment by zhangchenglin** [comment]
> Yes. I plan to do so. However I will not accept any "Feature Request"; Meaning don't expect any new features from me. But I will make it compatible with any new PHP versions and as well as fix any bugs that are worth fixing.



What is the difference between you and him?
 Is it necessary to make wheels again?

**Comment by Dibbyo456** [comment]
> What is the difference between you and him?

He is the original author of this project. All I did was fix couple of bugs and added some more features. So all the credits goes to him and the people who contributed in the project. If you don't need the additional 2 new methods I added, then you can also use the original project.

> Is it necessary to make wheels again?

I'm sorry, what?

**Comment by zhangchenglin** [comment]
Yours is very good, and hiss is also very good.
 I originally thought you were rewriting those functions again, so I said that the wheel was repeated.

**Pull request closed without merging**
